spring.application.name=peertubeminer
server.port=8081
videominer.base.url=http://localhost:8080/videominer/api

peertubeminer.baseuri=https://peertube.tv/api/v1

peertubeminer.maxVideos = 10
peertubeminer.maxComments = 10

videominer.uri=http://localhost:8080/videominer/channels